<h1>RECORDS OF UPDATEING...</h1>
<ul>
    <li>using file: <b style="color: red">auto_labeled_sort_with_box_office_1997-2017.csv</b>
    </li>
</ul>
<p>
num_to_Rnum_dict = {'Rnum_year_box_office_label': { 9:'R9', 8:'R8', 7:'R7', 6:'R6', 5:'R5', 4:'R4', 3:'R3', 2:'R2', 1:'R1', 0:'R0' }}      # label = column name
df_10038.replace(num_to_Rnum_dict, inplace = True)</p>

In [1]:
import os
import requests
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
from math import log
from collections import Counter

%matplotlib inline

In [ ]:
CONFIG_PATTERN = 'http://api.themoviedb.org/3/configuration?api_key=e7a9762dabfdc186e180a0791bb06e7c' 
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'

def _get_json(url):
    r = requests.get(url)
    return r.json()
    
def _download_images(urls, year, Rnum, group_num):
    """download all images in list 'urls' to 'path' """
    #path='train/'
    re = requests.get(urls[0])#get the first one pic of url
    def get_first_pic(r, num_i, group_num, count_test = 0):
        filetype = r.headers['content-type'].split('/')[-1]
        threshold = int(len(df_sort_y_Rnum.get_group((year, Rnum)))*0.8)
        print('threshold: ', threshold)
        if group_num < threshold:
                print('num_i: ', num_i)
                filename = '{0}.{1}.{2}.{3}'.format(Rnum, group_num, year, filetype)
                path = 'train/'
                filepath = os.path.join(path, filename)
                print('filepath: ',filepath)
                with open(filepath,'wb') as w:
                    w.write(r.content)
                    print('OK')
        else:
            print('num_i: ', num_i)
            filename = '{0}.{1}'.format(num_i, filetype)
            path = 'test/'
            filepath = os.path.join(path, filename)
            print('count_test: ', count_test)
            print('filepath: ',filepath)
            with open(filepath,'wb') as w:
                w.write(r.content)
                print('OK')
        print('now I have downloaded the first movie poster of number', i)
    get_first_pic(re, i, list_of_group[i])
    
def get_poster_urls(imdbid):
    config = _get_json(CONFIG_PATTERN.format(key=KEY))
    IMG_PATTERN = 'http://api.themoviedb.org/3/movie/' + imdbid + '/images?api_key=e7a9762dabfdc186e180a0791bb06e7c'
    base_url = config['images']['base_url']
    sizes = config['images']['poster_sizes']

    def size_str_to_int(x):
        return float("inf") if x == 'original' else int(x[1:])
    max_size = max(sizes, key=size_str_to_int)

    posters = _get_json(IMG_PATTERN.format(key=KEY,imdbid=imdbid))['posters']
    poster_urls = []
    for poster in posters:
        rel_path = poster['file_path']
        url = "{0}{1}{2}".format(base_url, max_size, rel_path)
        poster_urls.append(url) 

    return poster_urls

def tmdb_posters(imdbid, count=None, outpath='.'): 
    urls = get_poster_urls(imdbid)
    if count is not None:
        urls = urls[:count]
    _download_images(urls, list_of_year[i], list_of_Rnum[i], list_of_group[i])
    
def get_id_from_file_n_create_dataframe(address):
    df = pd.read_csv(address)
    list_of_id = df.imdb_id
    list_of_year = df.year
    list_of_Rnum = df.Rnum_year_box_office_label
    list_of_group = df.groups_num
    return df, list_of_id, list_of_year, list_of_Rnum, list_of_group

if __name__=="__main__":
    print('---STAR---')
    print()
    print('...Ready to get IMDb id from file')
    df, list_of_movie_id, list_of_year, list_of_Rnum, list_of_group = get_id_from_file_n_create_dataframe('v3_auto_labeled_sort_with_box_office_1997-2017.csv')
    print('Sucess...')
    print()
    print('...Ready to group the new dataframa by "year" and "Rnum_year_box_office_label"')
    df_sort_y_Rnum = df_10038.groupby(['year', 'Rnum_year_box_office_label'])
    print('Sucess...')
    print()
    print('...Ready to download the movie poster in individual movie')
    for i in range(, 1020):
        print('now is the number ' , i+1 , ' : ', list_of_movie_id[i])
        tmdb_posters(list_of_movie_id[i])
        print('***now the execution have done this time in the local host***')
        print()
    print('---FINISHED---')

In [4]:
df_10038

,Unnamed: 0,Unnamed: 0.1,previous_index_num,movie_title_txt_num,imdb_id,number_of _posters,total_box_office,with_adjusted_box_office,total_label,year,movie_title,year_box_office_label,Rnum_year_box_office_label,groups_num,train_or_test
0,0,0,0,1,tt1825683,108,1273623549,1273623549,9,2017,Black Panther,9,R9,0,N/A
1,1,1,8,9,tt3469046,80,1034542646,1034542646,9,2017,Despicable Me 3,9,R9,1,N/A
2,2,2,6451,6790,tt7131870,14,861434171,861434171,9,2017,Zhan Lang 2,9,R9,2,N/A
3,3,3,13,14,tt3501632,105,850653412,850653412,9,2017,Thor Ragnarok,9,R9,3,N/A
4,4,4,4,5,tt2380307,71,780299991,780299991,9,2017,Coco,9,R9,4,N/A
5,5,5,41,42,tt1396484,79,697459228,697459228,9,2017,It,9,R9,5,N/A
6,6,6,12,13,tt0974015,151,655953446,655953446,9,2017,Justice League,9,R9,6,N/A
7,7,7,38,39,tt3371366,112,603968683,603968683,9,2017,Transformers The Last Knight,9,R9,7,N/A
8,8,8,25,26,tt5013056,56,499518504,499518504,9,2017,Dunkirk,9,R9,8,N/A
9,9,9,7,8,tt3450958,86,490280162,490280162,9,2017,War for the Planet of the Apes,9,R9,9,N/A
10,10,10,26,27,tt4649466,106,408834838,408834838,9,2017,Kingsman The Golden Circle,9,R9,10,N/A
11,11,11,5695,5967,tt3606752,81,383601115,383601115,9,2017,Cars 3,9,R9,11,N/A
12,12,12,17,18,tt4477536,44,368222687,368224217,9,2017,Fifty Shades Freed,9,R9,12,N/A
13,13,13,6284,6601,tt6170484,3,360687719,360687719,9,2017,Zhuo yao ji 2,9,R9,13,N/A
14,14,14,22,23,tt3402236,94,349213586,349213586,9,2017,Murder on the Orient Express,9,R9,14,N/A
15,15,15,6749,7124,tt7431894,2,333299054,333299054,9,2017,Never Say Die,9,R9,15,N/A
16,16,16,5,6,tt3411444,53,290816813,290816813,9,2017,Ferdinand,9,R9,16,N/A
17,17,17,15,16,tt4500922,59,283923129,283923129,9,2017,Maze Runner The Death Cure,9,R9,17,N/A
18,18,18,14,15,tt1856101,99,259143008,259143008,9,2017,Blade Runner 2049,9,R9,18,N/A
19,19,19,33,34,tt1365519,35,246895273,246895273,9,2017,Tomb Raider,9,R9,19,N/A
20,20,20,42,43,tt5117670,47,229932640,229932640,9,2017,Peter Rabbit,9,R9,20,N/A
21,21,21,1,2,tt3890160,79,228104185,228104185,9,2017,Baby Driver,9,R9,21,N/A
22,22,22,6635,6992,tt0076570,1,223414744,223414744,9,2017,Fang Hua,9,R9,22,N/A
23,23,23,9,10,tt1981128,55,220800160,220800160,9,2017,Geostorm,9,R9,23,N/A
24,24,24,30,31,tt4877122,42,216807812,216807812,9,2017,Emoji Movie The,9,R9,24,N/A
25,25,25,20,21,tt2239822,106,215116144,215116144,9,2017,Valerian and the City of a Thousand Planets,9,R9,25,N/A
26,26,26,11,12,tt2557478,48,214600188,214600188,9,2017,Pacific Rim Uprising,9,R9,26,N/A
27,27,27,6327,6647,tt4468740,34,198849356,198849356,9,2017,Paddington 2,9,R9,27,N/A
28,28,28,61,62,tt5580390,71,190500483,190500483,9,2017,Shape of Water The,9,R9,28,N/A
29,29,29,5669,5940,tt4765284,26,184716782,184716782,9,2017,Pitch Perfect 3,9,R9,29,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10008,10008,10008,5364,5591,tt0113184,2,3657,6988,0,1998,Go Now,0,R0,11,N/A
10009,10009,10009,5372,5601,tt0119547,7,3526,6736,0,1998,Little Boy Blue,0,R0,12,N/A
10010,10010,10010,5381,5612,tt0169156,1,3350,5570,0,1998,Quarry The,0,R0,13,N/A
10011,10011,10011,5382,5613,tt0116538,3,3348,6396,0,1998,Hit Me,0,R0,14,N/A
10012,10012,10012,5399,5631,tt0120219,1,3073,5875,0,1998,Storefront Hitchcock,0,R0,15,N/A
10013,10013,10013,5421,5655,tt0116833,4,2647,5059,0,1998,Last of the High Kings The,0,R0,16,N/A
10014,10014,10014,5440,5677,tt0162050,1,2442,3866,0,1998,Yom Yom,0,R0,17,N/A
10015,10015,10015,5462,5702,tt0040724,24,2197,4198,0,1998,River Red,0,R0,18,N/A
10016,10016,10016,5463,5703,tt0122710,1,2194,4189,0,1998,Shopping for Fangs,0,R0,19,N/A
10017,10017,10017,5476,5717,tt0124901,17,1971,3767,0,1998,Thursday,0,R0,20,N/A
10018,10018,10018,5487,5729,tt0146664,2,1742,2897,0,1998,Day Silence Died The,0,R0,21,N/A
10019,10019,10019,5183,5387,tt0091149,40,6707,13105,0,1997,Mouse The,0,R0,0,N/A
10020,10020,10020,5259,5471,tt0119401,1,5000,9768,0,1997,James Gang The,0,R0,1,N/A
10021,10021,10021,5265,5477,tt0118811,5,5000,9768,0,1997,Call of the Wild Dog of the Yukon The,0,R0,2,N/A
10022,10022,10022,5269,5483,tt7253216,1,5000,9768,0,1997,Guy,0,R0,3,N/A
10023,10023,10023,5270,5484,tt0113646,2,5000,9768,0,1997,Lewis and Clark and George,0,R0,4,N/A
10024,10024,10024,5273,5487,tt0111453,3,5000,9768,0,1997,Tollbooth,0,R0,5,N/A
10025,10025,10025,5278,5492,tt0115801,1,5000,9768,0,1997,Cadillac Ranch,0,R0,6,N/A
10026,10026,10026,5279,5493,tt0115832,3,5000,9768,0,1997,Carlas Song,0,R0,7,N/A
10027,10027,10027,5281,5495,tt0118042,1,5000,9768,0,1997,Unforgotten Twenty Five Years After Willowbrook,0,R0,8,N/A
10028,10028,10028,5282,5497,tt0118772,2,5000,9768,0,1997,Breaking Up,0,R0,9,N/A
10029,10029,10029,5285,5500,tt0112907,3,5000,9768,0,1997,Drunks,0,R0,10,N/A
10030,10030,10030,5288,5503,tt0118958,1,5000,9768,0,1997,Deli The,0,R0,11,N/A
10031,10031,10031,5290,5505,tt0116356,2,5000,9768,0,1997,Frankenstein and Me,0,R0,12,N/A
10032,10032,10032,10235,14127,tt0119227,9,5000,9768,0,1997,Grimm Brothers Snow White The,0,R0,13,N/A
10033,10033,10033,5365,5592,tt0119327,2,3620,7068,0,1997,Hugo Pool,0,R0,14,N/A
10034,10034,10034,5467,5708,tt0028905,1,2126,3534,0,1997,Homme Nu L,0,R0,15,N/A
10035,10035,10035,5548,5800,tt0130297,1,967,1606,0,1997,Sweet Jane,0,R0,16,N/A
10036,10036,10036,5576,5839,tt0118870,3,552,1076,0,1997,Cold Around the Heart,0,R0,17,N/A
10037,10037,10037,5588,5854,tt0120376,2,217,422,0,1997,Trojan War,0,R0,18,N/A

In [2]:
df_10038 = pd.read_csv('v3_auto_labeled_sort_with_box_office_1997-2017.csv')

In [3]:
df_10038['train_or_test'] = 'N/A'

In [5]:
df_sort_y_Rnum = df_10038.groupby(['year', 'Rnum_year_box_office_label'])

In [ ]:
spci = df_sort_y_Rnum.get_group((1997, 'R0'))

In [ ]:
spci['groups_num'].index

In [ ]:
len(listtt)

In [ ]:
int(len(spci['groups_num'].index)*0.8)

In [ ]:
int(len(listtt)*0.8)

In [ ]:
listtt = list(spci['groups_num'].index)

In [ ]:
listtt[0]

In [6]:
df_sort_y_Rnum = df_10038.groupby(['year', 'Rnum_year_box_office_label'])

#len(index_num_list)
for sp_keys in df_sort_y_Rnum.groups.keys():
    print('sp_key: ',sp_keys)
    spcified_year_df = df_sort_y_Rnum.get_group(sp_keys)
    threshold = int(len(spcified_year_df)*0.8)
    index_num_list = spcified_year_df['groups_num'].index
    for index_i in range(0,len(index_num_list)):
        #print('index_i: ', index_i)
        value = index_num_list[index_i]
        if index_i < threshold:
            df_10038['train_or_test'][value] = 'train'
        else:
            df_10038['train_or_test'][value] = 'test'

sp_key:  (1997, 'R0')

/Users/linyujing/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/linyujing/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

sp_key:  (1997, 'R1')
sp_key:  (1997, 'R2')
sp_key:  (1997, 'R3')
sp_key:  (1997, 'R4')
sp_key:  (1997, 'R5')
sp_key:  (1997, 'R6')
sp_key:  (1997, 'R7')
sp_key:  (1997, 'R8')
sp_key:  (1997, 'R9')
sp_key:  (1998, 'R0')
sp_key:  (1998, 'R1')
sp_key:  (1998, 'R2')
sp_key:  (1998, 'R3')
sp_key:  (1998, 'R4')
sp_key:  (1998, 'R5')
sp_key:  (1998, 'R6')
sp_key:  (1998, 'R7')
sp_key:  (1998, 'R8')
sp_key:  (1998, 'R9')
sp_key:  (1999, 'R0')
sp_key:  (1999, 'R1')
sp_key:  (1999, 'R2')
sp_key:  (1999, 'R3')
sp_key:  (1999, 'R4')
sp_key:  (1999, 'R5')
sp_key:  (1999, 'R6')
sp_key:  (1999, 'R7')
sp_key:  (1999, 'R8')
sp_key:  (1999, 'R9')
sp_key:  (2000, 'R0')
sp_key:  (2000, 'R1')
sp_key:  (2000, 'R2')
sp_key:  (2000, 'R3')
sp_key:  (2000, 'R4')
sp_key:  (2000, 'R5')
sp_key:  (2000, 'R6')
sp_key:  (2000, 'R7')
sp_key:  (2000, 'R8')
sp_key:  (2000, 'R9')
sp_key:  (2001, 'R0')
sp_key:  (2001, 'R1')
sp_key:  (2001, 'R2')
sp_key:  (2001, 'R3')
sp_key:  (2001, 'R4')
sp_key:  (2001, 'R5')
sp_key:  (2001, 'R6')
sp_key:  (2001, 'R7')
sp_key:  (2001, 'R8')
sp_key:  (2001, 'R9')
sp_key:  (2002, 'R0')
sp_key:  (2002, 'R1')
sp_key:  (2002, 'R2')
sp_key:  (2002, 'R3')
sp_key:  (2002, 'R4')
sp_key:  (2002, 'R5')
sp_key:  (2002, 'R6')
sp_key:  (2002, 'R7')
sp_key:  (2002, 'R8')
sp_key:  (2002, 'R9')
sp_key:  (2003, 'R0')
sp_key:  (2003, 'R1')
sp_key:  (2003, 'R2')
sp_key:  (2003, 'R3')
sp_key:  (2003, 'R4')
sp_key:  (2003, 'R5')
sp_key:  (2003, 'R6')
sp_key:  (2003, 'R7')
sp_key:  (2003, 'R8')
sp_key:  (2003, 'R9')
sp_key:  (2004, 'R0')
sp_key:  (2004, 'R1')
sp_key:  (2004, 'R2')
sp_key:  (2004, 'R3')
sp_key:  (2004, 'R4')
sp_key:  (2004, 'R5')
sp_key:  (2004, 'R6')
sp_key:  (2004, 'R7')
sp_key:  (2004, 'R8')
sp_key:  (2004, 'R9')
sp_key:  (2005, 'R0')
sp_key:  (2005, 'R1')
sp_key:  (2005, 'R2')
sp_key:  (2005, 'R3')
sp_key:  (2005, 'R4')
sp_key:  (2005, 'R5')
sp_key:  (2005, 'R6')
sp_key:  (2005, 'R7')
sp_key:  (2005, 'R8')
sp_key:  (2005, 'R9')
sp_key:  (2006, 'R0')
sp_key:  (2006, 'R1')
sp_key:  (2006, 'R2')
sp_key:  (2006, 'R3')
sp_key:  (2006, 'R4')
sp_key:  (2006, 'R5')
sp_key:  (2006, 'R6')
sp_key:  (2006, 'R7')
sp_key:  (2006, 'R8')
sp_key:  (2006, 'R9')
sp_key:  (2007, 'R0')
sp_key:  (2007, 'R1')
sp_key:  (2007, 'R2')
sp_key:  (2007, 'R3')
sp_key:  (2007, 'R4')
sp_key:  (2007, 'R5')
sp_key:  (2007, 'R6')
sp_key:  (2007, 'R7')
sp_key:  (2007, 'R8')
sp_key:  (2007, 'R9')
sp_key:  (2008, 'R0')
sp_key:  (2008, 'R1')
sp_key:  (2008, 'R2')
sp_key:  (2008, 'R3')
sp_key:  (2008, 'R4')
sp_key:  (2008, 'R5')
sp_key:  (2008, 'R6')
sp_key:  (2008, 'R7')
sp_key:  (2008, 'R8')
sp_key:  (2008, 'R9')
sp_key:  (2009, 'R0')
sp_key:  (2009, 'R1')
sp_key:  (2009, 'R2')
sp_key:  (2009, 'R3')
sp_key:  (2009, 'R4')
sp_key:  (2009, 'R5')
sp_key:  (2009, 'R6')
sp_key:  (2009, 'R7')
sp_key:  (2009, 'R8')
sp_key:  (2009, 'R9')
sp_key:  (2010, 'R0')
sp_key:  (2010, 'R1')
sp_key:  (2010, 'R2')
sp_key:  (2010, 'R3')
sp_key:  (2010, 'R4')
sp_key:  (2010, 'R5')
sp_key:  (2010, 'R6')
sp_key:  (2010, 'R7')
sp_key:  (2010, 'R8')
sp_key:  (2010, 'R9')
sp_key:  (2011, 'R0')
sp_key:  (2011, 'R1')
sp_key:  (2011, 'R2')
sp_key:  (2011, 'R3')
sp_key:  (2011, 'R4')
sp_key:  (2011, 'R5')
sp_key:  (2011, 'R6')
sp_key:  (2011, 'R7')
sp_key:  (2011, 'R8')
sp_key:  (2011, 'R9')
sp_key:  (2012, 'R0')
sp_key:  (2012, 'R1')
sp_key:  (2012, 'R2')
sp_key:  (2012, 'R3')
sp_key:  (2012, 'R4')
sp_key:  (2012, 'R5')
sp_key:  (2012, 'R6')
sp_key:  (2012, 'R7')
sp_key:  (2012, 'R8')
sp_key:  (2012, 'R9')
sp_key:  (2013, 'R0')
sp_key:  (2013, 'R1')
sp_key:  (2013, 'R2')
sp_key:  (2013, 'R3')
sp_key:  (2013, 'R4')
sp_key:  (2013, 'R5')
sp_key:  (2013, 'R6')
sp_key:  (2013, 'R7')
sp_key:  (2013, 'R8')
sp_key:  (2013, 'R9')
sp_key:  (2014, 'R0')
sp_key:  (2014, 'R1')
sp_key:  (2014, 'R2')
sp_key:  (2014, 'R3')
sp_key:  (2014, 'R4')
sp_key:  (2014, 'R5')
sp_key:  (2014, 'R6')
sp_key:  (2014, 'R7')
sp_key:  (2014, 'R8')
sp_key:  (2014, 'R9')
sp_key:  (2015, 'R0')
sp_key:  (2015, 'R1')
sp_key:  (2015, 'R2')
sp_key:  (2015, 'R3')
sp_key:  (2015, 'R4')
sp_key:  (2015, 'R5')
sp_key:  (2015, 'R6')
sp_key:  (2015, 'R7')
sp_key:  (2015, 'R8')
sp_key:  (2015, 'R9')
sp_key:  (2016, 'R0')
sp_key:  (2016, 'R1')
sp_key:  (2016, 'R2')
sp_key:  (2016, 'R3')
sp_key:  (2016, 'R4')
sp_key:  (2016, 'R5')
sp_key:  (2016, 'R6')
sp_key:  (2016, 'R7')
sp_key:  (2016, 'R8')
sp_key:  (2016, 'R9')
sp_key:  (2017, 'R0')
sp_key:  (2017, 'R1')
sp_key:  (2017, 'R2')
sp_key:  (2017, 'R3')
sp_key:  (2017, 'R4')
sp_key:  (2017, 'R5')
sp_key:  (2017, 'R6')
sp_key:  (2017, 'R7')
sp_key:  (2017, 'R8')
sp_key:  (2017, 'R9')

In [ ]:
df_10038.head()

In [7]:
df_10038.to_csv('v6_auto_labeled_sort_with_box_office_1997-2017.csv')

In [ ]:
#just download one pic of every movie
#testing the function of try-except is work or now, I add an IMDb ID into the testing file(test_9_image_poster_download.txt)
#the worong number of IMDb ID is 3(in arrary is 2)


CONFIG_PATTERN = 'http://api.themoviedb.org/3/configuration?api_key=e7a9762dabfdc186e180a0791bb06e7c' 
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'

def _get_json(url):
    r = requests.get(url)
    return r.json()
    
def _download_images(urls, path='.'):
    """download all images in list 'urls' to 'path' """
    print('total number of image: ' , len(urls))
    number_of_poster = len(urls)
    csv_writer.writerow([i+1, list_of_movie_id[i], number_of_poster])
    
    re = requests.get(urls[0])#get the first one pic of url
    def get_first_pic(r, num_i):
        filetype = r.headers['content-type'].split('/')[-1]
        filename = 'num{0}.poster.{1}'.format(num_i+1, filetype)
        filepath = os.path.join(path, filename)
        with open(filepath,'wb') as w:
            w.write(r.content)
            print('OK')
        print('now I have downloaded the first movie poster of number', i)
    get_first_pic(re, i)
    
def get_poster_urls(imdbid):
    config = _get_json(CONFIG_PATTERN.format(key=KEY))
    IMG_PATTERN = 'http://api.themoviedb.org/3/movie/' + imdbid + '/images?api_key=e7a9762dabfdc186e180a0791bb06e7c'
    base_url = config['images']['base_url']
    sizes = config['images']['poster_sizes']

    def size_str_to_int(x):
        return float("inf") if x == 'original' else int(x[1:])
    max_size = max(sizes, key=size_str_to_int)

    posters = _get_json(IMG_PATTERN.format(key=KEY,imdbid=imdbid))['posters']
    poster_urls = []
    for poster in posters:
        rel_path = poster['file_path']
        url = "{0}{1}{2}".format(base_url, max_size, rel_path)
        poster_urls.append(url) 

    return poster_urls

def tmdb_posters(imdbid, count=None, outpath='.'): 
    urls = get_poster_urls(imdbid)
    if count is not None:
        urls = urls[:count]
    _download_images(urls, outpath)
    
def get_id_from_file(address):
    f= open(address, encoding = 'utf8')#讀所有詞
    s = f.read()
    #print(s)
    spilt_s = s.split("\n")
    return spilt_s

if __name__=="__main__":
    print('---STAR---')
    print('ready to get IMDb id from file...')
    list_of_movie_id = get_id_from_file('test_9_image_poster_download.txt')
    print('sucess')
    print('ready to download the movie poster in individual movie...')
    error_list = []
    with open( 'number_of_poster_in_range_test.csv', 'w' , encoding='UTF-8', newline='') as csv_file:
        csv_writer = csv.writer(csv_file)
        fileHeader = ['num', 'imdb_id' , 'number_of _posters']
        csv_writer.writerow(fileHeader)
        for i in range(0, len(list_of_movie_id)):
            try:
                print('now is the number ' , i+1 , ' : ')
                tmdb_posters(list_of_movie_id[i])
                print('***now the execution have done this time in the local host***')
                print()
            except:
                print('ERROR: CAN NOT not find any pic in ' , i+1)
                error_list.append([i+1, list_of_movie_id[i+1]])
                print()
    print('---FINISHED---')

In [ ]:
error_list[0]

In [ ]:
#download every pics of evrey movie

import os
import requests

CONFIG_PATTERN = 'http://api.themoviedb.org/3/configuration?api_key=e7a9762dabfdc186e180a0791bb06e7c' 
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'

def _get_json(url):
    r = requests.get(url)
    return r.json()
    
def _download_images(urls, path='.'):
    """download all images in list 'urls' to 'path' """
    for nr, url in enumerate(urls):
        r = requests.get(url)
        filetype = r.headers['content-type'].split('/')[-1]
        filename = 'TOP{0}_poster_{1}.{2}'.format(i, nr+1, filetype)
        filepath = os.path.join(path, filename)
        with open(filepath,'wb') as w:
            w.write(r.content)
        print('now the name of pic is ', filename)
        
def get_poster_urls(imdbid):
    config = _get_json(CONFIG_PATTERN.format(key=KEY))
    IMG_PATTERN = 'http://api.themoviedb.org/3/movie/' + imdbid + '/images?api_key=e7a9762dabfdc186e180a0791bb06e7c'
    base_url = config['images']['base_url']
    sizes = config['images']['poster_sizes']

    def size_str_to_int(x):
        return float("inf") if x == 'original' else int(x[1:])
    max_size = max(sizes, key=size_str_to_int)

    posters = _get_json(IMG_PATTERN.format(key=KEY,imdbid=imdbid))['posters']
    poster_urls = []
    for poster in posters:
        rel_path = poster['file_path']
        url = "{0}{1}{2}".format(base_url, max_size, rel_path)
        poster_urls.append(url) 

    return poster_urls

def tmdb_posters(imdbid, count=None, outpath='.'): 
    urls = get_poster_urls(imdbid)
    if count is not None:
        urls = urls[:count]
    _download_images(urls, outpath)
    
def get_id_from_file(address):
    f= open(address, encoding = 'utf8')#讀所有詞
    s = f.read()
    #print(s)
    spilt_s = s.split("\n")
    return spilt_s

if __name__=="__main__":
    print('---STAR---')
    print('ready to get IMDb id from file...')
    list_of_movie_id = get_id_from_file('test_9_image_poster_download.txt')
    print('sucess')
    print('ready to download the movie poster in individual movie...')
    for i in range(0, len(list_of_movie_id)):
        print('now is the number ' , i , ' : ')
        tmdb_posters(list_of_movie_id[i])
        print('***now the execution have done this time in the local host***')
    print('---FINISHED---')

In [ ]:
import requests
CONFIG_PATTERN = 'https://api.themoviedb.org/3/authentication/token/new?api_key=e7a9762dabfdc186e180a0791bb06e7c'
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'

url = CONFIG_PATTERN.format(key=KEY)
r = requests.get(url)
config = r.json()

In [ ]:
config

In [ ]:
http://api.themoviedb.org/3/movie/<imdbid>/images?api_key=<key>

In [ ]:
import requests
CONFIG_PATTERN = 'https://api.themoviedb.org/3/authentication/token/new?api_key=e7a9762dabfdc186e180a0791bb06e7c'
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'

imdb_id = 'tt0384814'
IMG_PATTERN = 'http://api.themoviedb.org/3/movie/' + imdb_id + '/images?api_key=e7a9762dabfdc186e180a0791bb06e7c' 
r = requests.get(IMG_PATTERN.format(key=KEY,imdbid=imdb_id))
api_response = r.json()

In [ ]:
len(api_response['backdrops'])

In [ ]:
api_response

In [ ]:
import os
import requests

CONFIG_PATTERN = 'http://api.themoviedb.org/3/configuration?api_key=e7a9762dabfdc186e180a0791bb06e7c'
IMG_PATTERN = 'http://api.themoviedb.org/3/movie/tt0468569/images?api_key=e7a9762dabfdc186e180a0791bb06e7c' 
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'
            
def _get_json(url):
    r = requests.get(url)
    return r.json()
    
def _download_images(urls, path='.'):
    """download all images in list 'urls' to 'path' """

    for nr, url in enumerate(urls):
        r = requests.get(url)
        filetype = r.headers['content-type'].split('/')[-1]
        filename = 'top4_poster_{0}.{1}'.format(nr+1,filetype)
        filepath = os.path.join(path, filename)
        with open(filepath,'wb') as w:
            w.write(r.content)

def get_poster_urls(imdbid):
    """ return image urls of posters for IMDB id

        returns all poster images from 'themoviedb.org'. Uses the
        maximum available size. 

        Args:
            imdbid (str): IMDB id of the movie

        Returns:
            list: list of urls to the images
    """
    config = _get_json(CONFIG_PATTERN.format(key=KEY))
    base_url = config['images']['base_url']
    sizes = config['images']['poster_sizes']

    """
        'sizes' should be sorted in ascending order, so
            max_size = sizes[-1]
        should get the largest size as well.        
    """
    def size_str_to_int(x):
        return float("inf") if x == 'original' else int(x[1:])
    max_size = max(sizes, key=size_str_to_int)

    posters = _get_json(IMG_PATTERN.format(key=KEY,imdbid=imdbid))['posters']
    poster_urls = []
    for poster in posters:
        rel_path = poster['file_path']
        url = "{0}{1}{2}".format(base_url, max_size, rel_path)
        poster_urls.append(url) 

    return poster_urls

def tmdb_posters(imdbid, count=None, outpath='.'):    
    urls = get_poster_urls(imdbid)
    if count is not None:
        urls = urls[:count]
    _download_images(urls, outpath)

if __name__=="__main__":
    tmdb_posters('tt0468569')

In [ ]:
import os
import requests

CONFIG_PATTERN = 'http://api.themoviedb.org/3/configuration?api_key=e7a9762dabfdc186e180a0791bb06e7c' 
KEY = '<e7a9762dabfdc186e180a0791bb06e7c>'
            
def _get_json(url):
    r = requests.get(url)
    return r.json()
    
def _download_images(urls, path='.'):
    """download all images in list 'urls' to 'path' """
    count_movie_num = 5 ####cuz i have done the download from 1 to 4
    for nr, url in enumerate(urls):
        r = requests.get(url)
        filetype = r.headers['content-type'].split('/')[-1]
        filename = 'top{0}_poster_{1}.{2}'.format(count_movie_num,  nr+1,filetype)
        filepath = os.path.join(path, filename)
        with open(filepath,'wb') as w:
            w.write(r.content)
    count_movie_num =  count_movie_num + 1

def get_poster_urls(imdbid):
    """ return image urls of posters for IMDB id

        returns all poster images from 'themoviedb.org'. Uses the
        maximum available size. 

        Args:
            imdbid (str): IMDB id of the movie

        Returns:
            list: list of urls to the images
    """
    config = _get_json(CONFIG_PATTERN.format(key=KEY))
    IMG_PATTERN = 'http://api.themoviedb.org/3/movie/' + imdbid + '/images?api_key=e7a9762dabfdc186e180a0791bb06e7c'
    base_url = config['images']['base_url']
    sizes = config['images']['poster_sizes']

    """
        'sizes' should be sorted in ascending order, so
            max_size = sizes[-1]
        should get the largest size as well.        
    """
    def size_str_to_int(x):
        return float("inf") if x == 'original' else int(x[1:])
    max_size = max(sizes, key=size_str_to_int)

    posters = _get_json(IMG_PATTERN.format(key=KEY,imdbid=imdbid))['posters']
    poster_urls = []
    for poster in posters:
        rel_path = poster['file_path']
        url = "{0}{1}{2}".format(base_url, max_size, rel_path)
        poster_urls.append(url) 

    return poster_urls

def tmdb_posters(imdbid, count=None, outpath='.'): 
    urls = get_poster_urls(imdbid)
    if count is not None:
        urls = urls[:count]
    _download_images(urls, outpath)
    
def get_id_from_file(address):
    f= open(address, encoding = 'utf8')#讀所有詞
    s = f.read()
    #print(s)
    spilt_s = s.split("\n")
    return spilt_s

if __name__=="__main__":
    print('---STAR---')
    print('ready to get IMDb id from file...')
    list_of_movie_id = get_id_from_file('imde_test_top250_id.txt')
    print('sucess')
    print('ready to download the movie poster in individual movie...')
    for i in range(0, len(list_of_movie_id)):
        #print('now is the number' + i + ': ')
        tmdb_posters(list_of_movie_id[i])
    print('---FINISHED---')

In [ ]:
f= open('imde_top250_id.txt', encoding = 'utf8')#讀所有詞
s = f.read()
#print(s)
spilt_s = s.split("\n")
spilt_s[1]

In [ ]:
'imde_top250_id.txt'